// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Useful to verify connectivity.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/list-patients.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_patients_default = defineTool2({
  name: "list_patients",
  title: "List patients",
  description: "List patients from the clinic, most recent first. Respects the signed-in staff member's access.",
  inputSchema: {
    search: z2.string().optional().describe("Optional name / phone / ID substring filter."),
    limit: z2.number().int().min(1).max(100).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("patients").select("id, first_name, last_name, phone, emirates_id, nationality, created_date").order("created_date", { ascending: false }).limit(limit ?? 20);
    if (search && search.trim().length > 0) {
      const s = search.trim();
      q = q.or(
        `first_name.ilike.%${s}%,last_name.ilike.%${s}%,phone.ilike.%${s}%,emirates_id.ilike.%${s}%`
      );
    }
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { patients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/today-schedule.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var today_schedule_default = defineTool3({
  name: "today_schedule",
  title: "Today's schedule",
  description: "Return today's appointments (UAE date) for the clinic. Respects the signed-in staff member's access.",
  inputSchema: {
    date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Optional YYYY-MM-DD date. Defaults to today in UAE time (+4).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const uaeToday = new Date(Date.now() + 4 * 60 * 60 * 1e3).toISOString().slice(0, 10);
    const day = date ?? uaeToday;
    const { data, error } = await supabaseForUser2(ctx).from("appointments").select("id, patient_name, phone, appointment_date, appointment_time, status, confirmation_status").eq("appointment_date", day).order("appointment_time", { ascending: true });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        { type: "text", text: `Appointments for ${day}: ${data?.length ?? 0}
${JSON.stringify(data ?? [], null, 2)}` }
      ],
      structuredContent: { date: day, appointments: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xnhtlotbmdteubpwowds";
var mcp_default = defineMcp({
  name: "cosmique-clinic-mcp",
  title: "Cosmique Clinic MCP",
  version: "0.1.0",
  instructions: "Tools for the Cosmique Aesthetics & Dermatology clinic management system. Use `echo` to verify connectivity, `list_patients` to search clinic patients, and `today_schedule` to view scheduled appointments. All tools act as the signed-in staff member and respect the app's data access rules.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [echo_default, list_patients_default, today_schedule_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
